name: CI - ms-pagamentos (crud)

on:
  pull_request:
    branches: ["main"]
    paths:
      - "ms-pagamentos/**"
      - ".github/workflows/**"
  push:
    branches: ["main"]
    paths:
      - "ms-pagamentos/**"
      - ".github/workflows/**"

jobs:
  build-ms-pagamentos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: "17"
          cache: maven

      - name: Build ms-pagamentos      
        run: mvn -f ms-pagamentos/pom.xml -B test
